// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using soru3.Data;

#nullable disable

namespace soru3.Migrations
{
    [DbContext(typeof(TaskDbContext))]
    [Migration("20251109132346_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("soru3.Data.Entites.ToDoTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ToDoTasks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Market alışverişini tamamla",
                            DueDate = new DateTime(2025, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCompleted = false,
                            Title = "Alışveriş Yap"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Elektrik ve internet faturalarını öde",
                            DueDate = new DateTime(2025, 11, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCompleted = false,
                            Title = "Faturaları Öde"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Saat 14:00'te proje toplantısına katıl",
                            DueDate = new DateTime(2025, 11, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCompleted = true,
                            Title = "Toplantıya Katıl"
                        },
                        new
                        {
                            Id = 4,
                            Description = "30 dakika yürüyüş yap",
                            DueDate = new DateTime(2025, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCompleted = false,
                            Title = "Egzersiz Yap"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Her gün 20 sayfa kitap oku",
                            DueDate = new DateTime(2025, 10, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCompleted = true,
                            Title = "Kitap Oku"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Gelen kutusunu düzenle ve önemli mailleri yanıtla",
                            DueDate = new DateTime(2025, 11, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCompleted = false,
                            Title = "E-posta Kontrolü"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Pazartesi toplantısı için PowerPoint sunumunu hazırla",
                            DueDate = new DateTime(2025, 11, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCompleted = false,
                            Title = "Sunum Hazırla"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Yağ ve filtre değişimi yaptır",
                            DueDate = new DateTime(2025, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCompleted = false,
                            Title = "Araç Bakımı"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Uzun zamandır konuşmadığın bir arkadaşını ara",
                            DueDate = new DateTime(2025, 10, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCompleted = true,
                            Title = "Arkadaşını Ara"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Listendeki filmi izle ve notlarını al",
                            DueDate = new DateTime(2025, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCompleted = false,
                            Title = "Film İzle"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
