// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using chat.Data;

#nullable disable

namespace chat.Migrations
{
    [DbContext(typeof(BookDbContext))]
    partial class BookDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("chat.Data.Entity.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .HasColumnType("TEXT");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PublishedYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "George Orwell",
                            Genre = "Dystopian",
                            PublishedYear = 1949,
                            Title = "1984"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Harper Lee",
                            Genre = "Classic",
                            PublishedYear = 1960,
                            Title = "To Kill a Mockingbird"
                        },
                        new
                        {
                            Id = 3,
                            Author = "F. Scott Fitzgerald",
                            Genre = "Novel",
                            PublishedYear = 1925,
                            Title = "The Great Gatsby"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Herman Melville",
                            Genre = "Adventure",
                            PublishedYear = 1851,
                            Title = "Moby-Dick"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Jane Austen",
                            Genre = "Romance",
                            PublishedYear = 1813,
                            Title = "Pride and Prejudice"
                        },
                        new
                        {
                            Id = 6,
                            Author = "J.D. Salinger",
                            Genre = "Fiction",
                            PublishedYear = 1951,
                            Title = "The Catcher in the Rye"
                        },
                        new
                        {
                            Id = 7,
                            Author = "J.R.R. Tolkien",
                            Genre = "Fantasy",
                            PublishedYear = 1937,
                            Title = "The Hobbit"
                        },
                        new
                        {
                            Id = 8,
                            Author = "Aldous Huxley",
                            Genre = "Science Fiction",
                            PublishedYear = 1932,
                            Title = "Brave New World"
                        },
                        new
                        {
                            Id = 9,
                            Author = "Paulo Coelho",
                            Genre = "Philosophical",
                            PublishedYear = 1988,
                            Title = "The Alchemist"
                        },
                        new
                        {
                            Id = 10,
                            Author = "Fyodor Dostoevsky",
                            Genre = "Psychological",
                            PublishedYear = 1866,
                            Title = "Crime and Punishment"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
