// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using soru2.Data;

#nullable disable

namespace soru2.Migrations
{
    [DbContext(typeof(PostContext))]
    [Migration("20251109095414_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("soru2.Data.Entites.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PuslishedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Ahmet Yılmaz",
                            Content = "Yapay zeka hayatımızın her alanına girmeye başladı.",
                            PuslishedDate = new DateTime(2025, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Yapay Zekanın Geleceği"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Elif Demir",
                            Content = "Microsoft, C# dilinde performans ve minimal kod odaklı yeni özellikler tanıttı.",
                            PuslishedDate = new DateTime(2025, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "C# 13 Yenilikleri"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Murat Kaya",
                            Content = "Web API geliştirme sürecinde dikkat edilmesi gereken en önemli noktaları derledik.",
                            PuslishedDate = new DateTime(2025, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "ASP.NET Core ile Web API"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Selin Aydın",
                            Content = "EF Core, ORM yapısı sayesinde veritabanı işlemlerini kolaylaştırır.",
                            PuslishedDate = new DateTime(2025, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Entity Framework Core Nedir?"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Kemal Özkan",
                            Content = "ASP.NET Core 6 ile gelen Minimal API yapısını örneklerle anlattık.",
                            PuslishedDate = new DateTime(2025, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Minimal API Nedir?"
                        },
                        new
                        {
                            Id = 6,
                            Author = "Ayşe Gür",
                            Content = "Katmanlı mimari ile sürdürülebilir kod yapısı oluşturma rehberi.",
                            PuslishedDate = new DateTime(2025, 6, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Clean Architecture’a Giriş"
                        },
                        new
                        {
                            Id = 7,
                            Author = "Hasan Tunç",
                            Content = "LINQ, koleksiyonlar üzerinde sorgu yazmayı kolaylaştırır.",
                            PuslishedDate = new DateTime(2025, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "LINQ Sorgularını Anlamak"
                        },
                        new
                        {
                            Id = 8,
                            Author = "Zeynep Koç",
                            Content = "Bağımlılıkları yönetmenin en kolay yolu: DI tasarım deseni.",
                            PuslishedDate = new DateTime(2025, 8, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Dependency Injection Basitçe"
                        },
                        new
                        {
                            Id = 9,
                            Author = "Oğuzhan Arslan",
                            Content = "Birden fazla işlem tek bir iş biriminde toplandığında hata riski azalır.",
                            PuslishedDate = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Unit of Work Nedir?"
                        },
                        new
                        {
                            Id = 10,
                            Author = "Ceren Uçar",
                            Content = "Veritabanı erişimini soyutlayarak temiz kod yazmak artık çok kolay.",
                            PuslishedDate = new DateTime(2025, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Repository Pattern Kullanımı"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
