// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using soru5.Data;

#nullable disable

namespace soru5.Migrations
{
    [DbContext(typeof(CustomerDbContext))]
    partial class CustomerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("soru5.Data.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "ahmet.yilmaz@example.com",
                            FirstName = "Ahmet",
                            LastName = "Yılmaz",
                            PhoneNumber = "0532 111 2233"
                        },
                        new
                        {
                            Id = 2,
                            Email = "ayse.demir@example.com",
                            FirstName = "Ayşe",
                            LastName = "Demir",
                            PhoneNumber = "0543 222 3344"
                        },
                        new
                        {
                            Id = 3,
                            Email = "mehmet.kaya@example.com",
                            FirstName = "Mehmet",
                            LastName = "Kaya",
                            PhoneNumber = "0551 333 4455"
                        },
                        new
                        {
                            Id = 4,
                            Email = "fatma.sahin@example.com",
                            FirstName = "Fatma",
                            LastName = "Şahin",
                            PhoneNumber = "0505 444 5566"
                        },
                        new
                        {
                            Id = 5,
                            Email = "ali.celik@example.com",
                            FirstName = "Ali",
                            LastName = "Çelik",
                            PhoneNumber = "0530 555 6677"
                        },
                        new
                        {
                            Id = 6,
                            Email = "zeynep.aydin@example.com",
                            FirstName = "Zeynep",
                            LastName = "Aydın",
                            PhoneNumber = "0544 666 7788"
                        },
                        new
                        {
                            Id = 7,
                            Email = "emre.koc@example.com",
                            FirstName = "Emre",
                            LastName = "Koç",
                            PhoneNumber = "0522 777 8899"
                        },
                        new
                        {
                            Id = 8,
                            Email = "elif.arslan@example.com",
                            FirstName = "Elif",
                            LastName = "Arslan",
                            PhoneNumber = "0555 888 9900"
                        },
                        new
                        {
                            Id = 9,
                            Email = "hasan.dogan@example.com",
                            FirstName = "Hasan",
                            LastName = "Doğan",
                            PhoneNumber = "0531 999 0011"
                        },
                        new
                        {
                            Id = 10,
                            Email = "merve.kurt@example.com",
                            FirstName = "Merve",
                            LastName = "Kurt",
                            PhoneNumber = "0506 101 1122"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
