// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Soru1.Data;

#nullable disable

namespace Soru1.Migrations
{
    [DbContext(typeof(MovieContext))]
    partial class MovieContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("Soru1.Data.Entities.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Director")
                        .HasColumnType("TEXT");

                    b.Property<int>("ReleaseYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Director = "H. Moritz",
                            ReleaseYear = 2005,
                            Title = "Hızlı ve Öfkeli"
                        },
                        new
                        {
                            Id = 2,
                            Director = "Peter Jackson",
                            ReleaseYear = 2003,
                            Title = "Yüzüklerin Efendisi: Kralın Dönüşü"
                        },
                        new
                        {
                            Id = 3,
                            Director = "Christopher Nolan",
                            ReleaseYear = 2010,
                            Title = "Başlangıç"
                        },
                        new
                        {
                            Id = 4,
                            Director = "Lana Wachowski, Lilly Wachowski",
                            ReleaseYear = 1999,
                            Title = "Matrix"
                        },
                        new
                        {
                            Id = 5,
                            Director = "Ridley Scott",
                            ReleaseYear = 2000,
                            Title = "Gladyatör"
                        },
                        new
                        {
                            Id = 6,
                            Director = "James Cameron",
                            ReleaseYear = 2009,
                            Title = "Avatar"
                        },
                        new
                        {
                            Id = 7,
                            Director = "Todd Phillips",
                            ReleaseYear = 2019,
                            Title = "Joker"
                        },
                        new
                        {
                            Id = 8,
                            Director = "Christopher Nolan",
                            ReleaseYear = 2014,
                            Title = "Interstellar"
                        },
                        new
                        {
                            Id = 9,
                            Director = "Gore Verbinski",
                            ReleaseYear = 2003,
                            Title = "Karayip Korsanları: Siyah İnci'nin Laneti"
                        },
                        new
                        {
                            Id = 10,
                            Director = "James Cameron",
                            ReleaseYear = 1997,
                            Title = "Titanic"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
