// <auto-generated />
using ECommerce.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ECommerce.Data.Migrations
{
    [DbContext(typeof(ECommerceDbContext))]
    [Migration("20251123114248_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("ECommerce.Data.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "İstanbul",
                            Email = "sametece@developer.com",
                            FirstName = "Samet",
                            LastName = "Ece"
                        },
                        new
                        {
                            Id = 2,
                            City = "Ankara",
                            Email = "ahmet.yilmaz@example.com",
                            FirstName = "Ahmet",
                            LastName = "Yılmaz"
                        },
                        new
                        {
                            Id = 3,
                            City = "İzmir",
                            Email = "mehmet.demir@example.com",
                            FirstName = "Mehmet",
                            LastName = "Demir"
                        },
                        new
                        {
                            Id = 4,
                            City = "Bursa",
                            Email = "ayse.kara@example.com",
                            FirstName = "Ayşe",
                            LastName = "Kara"
                        },
                        new
                        {
                            Id = 5,
                            City = "Antalya",
                            Email = "fatma.celik@example.com",
                            FirstName = "Fatma",
                            LastName = "Çelik"
                        },
                        new
                        {
                            Id = 6,
                            City = "Eskişehir",
                            Email = "can.aydin@example.com",
                            FirstName = "Can",
                            LastName = "Aydın"
                        },
                        new
                        {
                            Id = 7,
                            City = "Konya",
                            Email = "merve.sahin@example.com",
                            FirstName = "Merve",
                            LastName = "Şahin"
                        },
                        new
                        {
                            Id = 8,
                            City = "Samsun",
                            Email = "ali.gunes@example.com",
                            FirstName = "Ali",
                            LastName = "Güneş"
                        },
                        new
                        {
                            Id = 9,
                            City = "Gaziantep",
                            Email = "zeynep.kurt@example.com",
                            FirstName = "Zeynep",
                            LastName = "Kurt"
                        },
                        new
                        {
                            Id = 10,
                            City = "Trabzon",
                            Email = "burak.tas@example.com",
                            FirstName = "Burak",
                            LastName = "Taş"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
