// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using soru4.Data;

#nullable disable

namespace soru4.Migrations
{
    [DbContext(typeof(MovieDbContext))]
    [Migration("20251109150455_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("soru4.Data.Entites.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Director")
                        .HasColumnType("TEXT");

                    b.Property<int>("ReleaseYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Director = "Christopher Nolan",
                            ReleaseYear = 2010,
                            Title = "Inception"
                        },
                        new
                        {
                            Id = 2,
                            Director = "Lana Wachowski, Lilly Wachowski",
                            ReleaseYear = 1999,
                            Title = "The Matrix"
                        },
                        new
                        {
                            Id = 3,
                            Director = "Christopher Nolan",
                            ReleaseYear = 2014,
                            Title = "Interstellar"
                        },
                        new
                        {
                            Id = 4,
                            Director = "Frank Darabont",
                            ReleaseYear = 1994,
                            Title = "The Shawshank Redemption"
                        },
                        new
                        {
                            Id = 5,
                            Director = "David Fincher",
                            ReleaseYear = 1999,
                            Title = "Fight Club"
                        },
                        new
                        {
                            Id = 6,
                            Director = "Robert Zemeckis",
                            ReleaseYear = 1994,
                            Title = "Forrest Gump"
                        },
                        new
                        {
                            Id = 7,
                            Director = "Christopher Nolan",
                            ReleaseYear = 2008,
                            Title = "The Dark Knight"
                        },
                        new
                        {
                            Id = 8,
                            Director = "Quentin Tarantino",
                            ReleaseYear = 1994,
                            Title = "Pulp Fiction"
                        },
                        new
                        {
                            Id = 9,
                            Director = "Ridley Scott",
                            ReleaseYear = 2000,
                            Title = "Gladiator"
                        },
                        new
                        {
                            Id = 10,
                            Director = "James Cameron",
                            ReleaseYear = 2009,
                            Title = "Avatar"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
